"""bulletin update

Revision ID: 51bb70713544
Revises: 
Create Date: 2024-10-01 18:34:05.182615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51bb70713544'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boletim_urna',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('evaluator_phone', sa.String(length=15), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('finished', sa.Boolean(), nullable=False),
    sa.Column('last_carg', sa.Integer(), nullable=False),
    sa.Column('last_party', sa.Integer(), nullable=True),
    sa.Column('open_steps', sa.JSON(), nullable=True),
    sa.Column('header', sa.JSON(), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evaluator',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=False),
    sa.Column('section', sa.String(length=5), nullable=False),
    sa.Column('zone', sa.String(length=5), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evaluator')
    op.drop_table('boletim_urna')
    # ### end Alembic commands ###
